version: '3.8'

services:
  server:
    image: samply/blaze:0.22.2
    ports:
      - "${BLAZE_PORT:-8080}:8080"
    volumes:
      - blaze-data:/app/data
    environment:
      - "BASE_URL=${BLAZE_BASE_URL:-http://server:8080}"
      - "ENFORCE_REFERENTIAL_INTEGRITY=${ENFORCE_REFERENTIAL_INTEGRITY:-true}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 5s
  flare:
    image: ghcr.io/medizininformatik-initiative/flare:2.0
    ports:
      - "${FLARE_PORT:-8082}:8080"
    volumes:
      - "./ontology:/app/ontology"
    environment:
      - "FLARE_FHIR_SERVER=http://server:8080/fhir"
    depends_on:
      server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/cache/stats"]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 5s

volumes:
  blaze-data:
