version: '3.8'

services:
  server:
    image: samply/blaze:0.22.2
    ports:
      - "${BLAZE_PORT:-8080}:8080"
    volumes:
      - blaze-data:/app/data
    environment:
      - "ENFORCE_REFERENTIAL_INTEGRITY=${ENFORCE_REFERENTIAL_INTEGRITY:-true}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 5s

volumes:
  blaze-data:
