version: '3.8'

services:
  fhirbase:
    image: fhirbase/fhirbase:latest
    ports:
      - "${POSTGRES_PORT:-8080}:3000"
    volumes:
      - ./data/ndjson:/fhirbase/data
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 5s