version: '3.8'

services:
  server:
    image: ghcr.io/linuxforhealth/fhir-server:5.1.1
    ports:
      - "${LINUX4HEALTH_PORT:-8443}:9443"
    environment:
      - "BOOTSTRAP_DB=true"
    healthcheck:
      test: [ "CMD", "curl", "-f", "-k", "https://localhost:9443/fhir-server/api/v4/metadata" ]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 5s
  flare:
    image: ghcr.io/medizininformatik-initiative/flare:2.0
    ports:
      - "${FLARE_PORT:-8082}:8080"
    environment:
      - "FLARE_FHIR_SERVER=https://localhost:${LINUX4HEALTH_PORT}/fhir-server/api/v4"
    depends_on:
      server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/cache/stats"]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 5s