version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "changeme"
      POSTGRES_USER: "fhiradmin"
      POSTGRES_DB: "fhirdb"
      PGUSER: "postgres"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database-setup/fhirdb.sql:/docker-entrypoint-initdb.d/fhirdb.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 5s

volumes:
  postgres-data:
