version: '3.8'

services:
  server:
    image: ghcr.io/linuxforhealth/fhir-server:5.1.1
    ports:
      - "${LINUX4HEALTH_PORT:-8443}:9443"
    environment:
      BATCH_DB_HOSTNAME: postgres
      BATCH_DB_NAME: fhirdb
      BATCH_DB_USER: fhirserver
      BATCH_DB_PASSWORD: change-password
    volumes:
      - ./config/configDropins/defaults:/opt/ol/wlp/usr/servers/defaultServer/configDropins/defaults
      - ./config/configDropins/overrides:/opt/ol/wlp/usr/servers/defaultServer/configDropins/overrides
      - ./config/default/fhir-server-config.json:/opt/ol/wlp/usr/servers/defaultServer/config/default/fhir-server-config.json
    healthcheck:
      test: curl --fail -k https://localhost:9443/fhir-server/api/v4/metadata || exit 1
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 5s
  flare:
    image: ghcr.io/medizininformatik-initiative/flare:2.0
    ports:
      - "${FLARE_PORT:-8082}:8080"
    environment:
      - "FLARE_FHIR_SERVER=https://localhost:${LINUX4HEALTH_PORT}/fhir-server/api/v4"
    depends_on:
      server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/cache/stats"]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 5s