version: '3.8'

services:
  hapifhir:
    image: hapiproject/hapi:latest
    ports:
      - "${HAPIFHIR_PORT:-8080}:8080"
    configs:
      - source: hapi
        target: /app/config/application.yaml
# No healthcheck since the container has no curl
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8080/fhir/metadata" ]
#      interval: 10s
#      timeout: 10s
#      retries: 30
#      start_period: 5s
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-admin}"
      POSTGRES_USER: "${POSTGRES_USER:-admin}"
      POSTGRES_DB: "${POSTGRES_DB:-hapi}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 5s
  flare:
    image: ghcr.io/medizininformatik-initiative/flare:2.0
    ports:
      - "${FLARE_PORT:-8082}:8080"
    environment:
      - "FLARE_FHIR_SERVER=https://localhost:${HAPIFHIR_PORT}/fhir"
#    depends_on:
#      hapifhir:
#        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/cache/stats"]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 5s

volumes:
  postgres-data:

configs:
  hapi:
    file: ./hapi.application.yaml
