spring:
  datasource:
    url: 'jdbc:postgresql://postgres:5432/hapi'
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
      hibernate.search.enabled: false

hapi:
  fhir:
    enforce_referential_integrity_on_write: false
    enforce_referential_integrity_on_delete: false