import sys
import os
import json
from urllib3 import PoolManager

########################################################################################################################
# Script for importing FHIR instance data generated by Synthea to CSIRO Pathling via the batch/transaction FHIR
# operation
########################################################################################################################


bundle_data_dir = 'fhir'
http = PoolManager()
headers = {'Content-Type': "application/fhir+json"}


def adjust_bundle_entry_request_element(bundle_data):
    bundle_json = json.loads(bundle_data)
    entry_element = bundle_json['entry']
    # Iterate over all entries and adjust request element by changing method to 'PUT' and url to '<resource type>/<id>'
    for entry in entry_element:
        resource_element = entry['resource']
        resource_type = resource_element['resourceType']
        resource_id = resource_element['id']
        request_element = entry['request']
        request_element['method'] = "PUT"
        request_element['url'] = resource_type + '/' + resource_id
    return json.dumps(bundle_json)


def upload_fhir_instance_data_to_pathling(url, output_path):
    bundle_data_path = os.path.join(output_path, bundle_data_dir)
    dir_content = os.listdir(bundle_data_path)
    print(f"Uploading {len(dir_content)} files from '{bundle_data_path}' to '{url}'")
    for file in dir_content:
        filename = os.fsdecode(file)
        try:
            if filename.endswith('.json'):
                # Load data from file
                full_path = os.path.join(bundle_data_path, filename)
                with open(os.path.join(full_path), encoding='utf8') as bundle_file:
                    bundle_data = bundle_file.read()
                    # Adjust request elements in Bundle instance
                    bundle_data = adjust_bundle_entry_request_element(bundle_data)
                    # Upload data to pathling
                    response = http.request(method='post', url=f"{url}?_format=application/json", headers=headers,
                                            body=bundle_data)
                    if response.status >= 400:
                        raise Exception(f"Request failed with status code {response.status}: {str(response.data)}")
                    else:
                        print(f"File '{filename}' uploaded successfully")
            else:
                raise Exception(f"Unexpected bundle file format: '{os.path.splitext(filename)}'. Expected 'json'")
        except Exception as e:
            print(f"Skipping bundle file '{full_path}': {str(e)}")
        break


if __name__ == "__main__":
    synthea_output_path = sys.argv[1]
    pathling_url = sys.argv[2]
    upload_fhir_instance_data_to_pathling(pathling_url, synthea_output_path)
